### PR TITLE
Np update pyinstaller

### PR DESCRIPTION
**Pull request by nick-pestell**
The main purpose of this PR is to investigate a potential fix of https://github.com/aphascience/autoshutdown/issues.

The potential fix is simply bumping pyinstaller to version 6.10.0. See `requirements/built.txt`.

I have also added a new feature which is to include the version number in the first line of the log output. This I think is useful as I wanted to interrogate the logs and know which version of the software produced which bits of the log. 

This basically works by copying `version.properties` in the distribution folder (see `build.sh`), then parsing the version number in `activate_cron` and sticking the version number in the cron file. It's then read in as an argument in `auto_off.py` and added to the first line of the log output. 

e.g.  `Starting auto-off routine: machine will shutdown after 30 minutes of inactivity` -> `Starting autoshutdown_v1.0.4: machine will shutdown after 30 minutes of inactivity`.

I've also updated tests for `activate_cron` so they work with this additional part of the cron file.

### CODE REVIEW

**Comment by jb2cool** [comment]
where did the change to the folder called _internal from the older _internals come from? was that just a typo before and it always had that name or is this something that changes when moving to the new pyinstaller?

**Comment by nick-pestell** [comment]
> where did the change to the folder called _internal from the older _internals come from? was that just a typo before and it always had that name or is this something that changes when moving to the new pyinstaller?

Yes, correcting typo in the readme. Should have stated that, sorry.

**Comment by jb2cool** [comment]
Looking at the built version of 1.0.3 i have already i think it was always called _internal so this was just a typo in the documentation.

**Comment by jb2cool** [comment]
Looking good to me, i don't actually understand too much of the python code (i'm not a big coder) but i don't see anything there that causes me any concern. Happy for this to be merged in and then another release tag created.

**Comment by jb2cool** [comment]
Can we delete the NP_update_pyinstaller branch too? I like keeping branches to a minumum else you end up like [this ](https://github.com/subsurface/subsurface/branches)

**Comment by jb2cool** [comment]
ah, you already did it

**Pull request merged**
